resolver: lts-20.4

ghc-options:
  "$locals": -Wall

packages:
- .

extra-deps:
  - unagi-chan-0.4.1.3
  - unagi-streams-0.2.7

system-ghc: false

extra-include-dirs: ["/usr/local/opt/openssl/include"]
extra-lib-dirs: ["/usr/local/opt/openssl/lib"]
